from decimal import Decimal

SIGNIFICANT_CHANGE_PCT = Decimal("20")
SIGNIFICANT_ABSOLUTE_SHARE_PCT = Decimal("5")
TOP_ONE_CONCENTRATION_PCT = Decimal("50")
TOP_THREE_CONCENTRATION_PCT = Decimal("80")
MIN_CONCENTRATION_DIMENSIONS = 4

MIN_OUTLIER_SAMPLE_SIZE = 8
IQR_MULTIPLIER = Decimal("1.5")

MAX_BUSINESS_INSIGHTS = 20
MAX_QUALITY_INSIGHTS = 10
MAX_OUTLIER_INSIGHTS = 6
